# Generated by Django 4.2.18 on 2025-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='paper/', verbose_name='文献文件'),
        ),
    ]
