# Generated by Django 4.2.18 on 2025-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_usersearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='文章关键词，多个关键词用逗号分隔', max_length=500, null=True),
        ),
    ]
